CREATE DATABASE employees_db;
USE employees_db;

CREATE TABLE departments(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
   name varchar(30) UNIQUE NOT NULL
);

CREATE TABLE roles(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL
    title varchar(30) UNIQUE NOT NULL
    salary DECIMAL UNSIGNED NOT NULL
    departmentId INT UNSIGNED NOT NULL
    FOREIGN KEY ( departmentId) REFERENCES departments
);